### ISSUE TITLE
ERROR ReferenceError: lists is not defined

### ISSUE THREAD

**Issue by GaiaAnn** [hubot-scripts/hubot-trello#15]
I can connect slack and trello (when I say "trello help",it can response me)
but when I use **trello help** command like **trello list lists** always got error
`[Fri Feb 24 2017 15:59:57 GMT+0800 (PHT)] ERROR ReferenceError: lists is not defined
  at TextListener.callback (/Users/Ann/myhubot/node_modules/hubot-trello-ddx/src/trello.coffee:93:5, <js>:99:26)
  at executeListener (/Users/Ann/myhubot/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/Users/Ann/myhubot/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /Users/Ann/myhubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/Users/Ann/myhubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/Users/Ann/myhubot/node_modules/async/lib/async.js:268:15)
  at /Users/Ann/myhubot/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by GaiaAnn** [comment]
I'm sorry. My source had some problem I don't know why..
After I remove and reinstall. It works now!
