### ISSUE TITLE
Issues with pulling boards

### ISSUE THREAD

**Issue by jimhopkinsjr** [hubot-scripts/hubot-trello#2]
Not sure if I'm not setting up hubot-trello correctly or not but I am getting error's when loading.  It also seems that Trello has changed the URL for boards to https://trello.com/b/<<board name>>/<<board id>>.

---

When Starting Hubot

---

[Thu Mar 05 2015 17:09:45 GMT-0600 (CST)] ERROR TypeError: Cannot call method 'toLowerCase' of undefined
  at /opt/hubot/node_modules/hubot-trello/src/trello.coffee:76:15, <js>:109:41
  at Request._callback (/opt/hubot/node_modules/hubot-trello/node_modules/node-trello/lib/node-trello.coffee:60:16)
  at Request.self.callback (/opt/hubot/node_modules/hubot-trello/node_modules/node-trello/node_modules/request/main.js:122:22)
  at Request.EventEmitter.emit (events.js:98:17)
  at Request.<anonymous> (/opt/hubot/node_modules/hubot-trello/node_modules/node-trello/node_modules/request/main.js:661:16)
  at Request.EventEmitter.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/opt/hubot/node_modules/hubot-trello/node_modules/node-trello/node_modules/request/main.js:623:14)
  at IncomingMessage.EventEmitter.emit (events.js:117:20)
  at _stream_readable.js:920:16
  at process._tickCallback (node.js:415:13)

---

When attempting to hubot trello list "backlog"

---

[Thu Mar 05 2015 17:12:00 GMT-0600 (CST)] ERROR TypeError: Cannot read property 'id' of undefined
  at showCards (/opt/hubot/node_modules/hubot-trello/src/trello.coffee:51:14, <js>:50:40)
  at TextListener.callback (/opt/hubot/node_modules/hubot-trello/src/trello.coffee:95:5, <js>:133:14)
  at TextListener.Listener.call (/opt/hubot/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/opt/hubot/node_modules/hubot/src/robot.coffee:197:9, <js>:143:33)
  at SlackBot.Adapter.receive (/opt/hubot/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at SlackBot.message (/opt/hubot/node_modules/hubot-slack/src/slack.coffee:154:20, <js>:189:21)
  at Client.<anonymous> (/opt/hubot/node_modules/hubot-slack/src/slack.coffee:1:1, <js>:3:61)
  at Client.EventEmitter.emit (events.js:95:17)
  at Client.onMessage (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/src/client.js:477:14)
  at WebSocket.<anonymous> (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/src/client.js:140:24)
  at WebSocket.EventEmitter.emit (events.js:98:17)
  at Receiver.self._receiver.ontext (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:697:10)
  at Receiver.opcodes.1.finish (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:397:14)
  at Receiver.expectHandler (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:384:31)
  at Receiver.add (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:93:24)
  at CleartextStream.firstHandler (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:678:22)
  at CleartextStream.EventEmitter.emit (events.js:95:17)
  at CleartextStream.<anonymous> (_stream_readable.js:746:14)
  at CleartextStream.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at _stream_readable.js:401:7
  at process._tickCallback (node.js:415:13)

**Comment by codeimpossible** [comment]
@jrhjr07 thanks for submitting this issue, i'll take a look at it ASAP.

**Comment by trfd** [comment]
I've been running with the same issue. In my case the env variable `HUBOT_TRELLO_BOARD` was not set correctly: only the **board id** is needed. To link the board `https://trello.com/b/oX6aX78Y/myboard`, the env var look like `export HUBOT_TRELLO_BOARD=oX6aX78Y`
Not sure if this can be of any help.

**Comment by codeimpossible** [comment]
@jrhjr07 can you confirm that setting the board id fixes your issue?

**Comment by syntax922** [comment]
I've been considering a change to my code base that would allow more flexibility with the boards and not require the env variable. Would be interested to know if this is a functionality that would be desired. I'm envisioning that you will still need the key and token, but from there we can get all of the boards and we can use the redis brain to store a "Default" board. Doing this will also allow to expand the ability to move cards between boards from hubot as well.
